[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: critical path tests
    regression: full test suite
    webrtc: WebRTC specific tests
addopts =
    -v --headed --slowmo=100
    -p no:randomly
